### ISSUE TITLE
Automatic build

### ISSUE THREAD

**Issue by majkinetor** [jftuga/less-Windows#1]
Are you willing to provide automated build when external repo changes ? 

You can setup all prereqs from chocolatey

**Comment by jftuga** [comment]
I've noticed that the upstream repo changes occur more often than actual releases.  I would like to automate builds when a new release is made.

Right now, this consists of me manually clone the repo, running `make` and then uploading the new binary to my release section.  This process will definitely not stand the test of time regarding getting new builds.

Do you know of a good CI/CD system that I could use to automate this process?  If not, I can do some research on this and get back to you.

Thanks.

**Comment by majkinetor** [comment]
You can automate builds on Gitlab which supports external repo with internal build file (I have on prem variant and I keep local Windows runners, not sure how it is on Gitlab.com) and for Windows I usually go with AppVeyor which has bunch of dev tools already installed and you can install anything else with chocolatey.

> I've noticed that the upstream repo changes occur more often than actual releases. I would like to automate builds when a new release is made.

Thats easy. Your automated build will simply exit without any release if [version.c](https://github.com/gwsw/less/blob/master/version.c) is not changed in that run.

Other then that, I suggest PowerShell automation via Invoke-Build (which is good to know as it is x-platform and can be used in general). I typically have lean build yaml files and do everything in `.build.ps1`.

**Comment by jftuga** [comment]
I would like attempt to have automatic builds done by either https://circleci.com/ or https://www.appveyor.com/.  Out of the box, it looks like these build systems support Visual Studio but mingw-w64.  In order to get `less` compiled with VS, a few changes need to be made in `Makefile.wnm`.  I have posted a issue with the maintainer.  Once this is corrected, I will try to proceed with an automated build.

https://github.com/gwsw/less/issues/61

**Comment by jftuga** [comment]
I am now using `AppVeyor` for automatic builds.  The `version_compare.py` script will run once per day.  It compares the version this repo is hosting against the [official less version](http://greenwoodsoftware.com/less/download.html).  If there is a new version, then `build.py` will download, compile, and create a new GitHub release containing `less.exe` and `lesskey.exe`.  If the versions are the same, then nothing will be updated.

I am currently tracking the `BETA` instead of the `RECOMMENDED` version as `v560` fixes a bug in which searches (with `/` key) were not being properly highlighted.  Once this version (or a newer one) becomes `RECOMMENDED`, I will switch over to `RECOMMENDED` instead of `BETA`.

See the repo if you want to review the Python scripts.  Does this satisfy all of the requirements in order to get this into [Chocolatey](https://chocolatey.org/)?

https://github.com/jftuga/less-Windows/releases

The `.1` at the end of the version is used by `AppVeyor`.  It needs a way to internally increment each build attempt.  I don't think there is a way around this.

**Comment by majkinetor** [comment]
> Does this satisfy all of the requirements in order to get this into Chocolatey?

Yes, chocolatey admins will not object to custom binaries that are taken from github and not listed officilly on site. Maybe you shold contact them to add the link there too, it will make it even more legit.

> The .1 at the end of the version is used by AppVeyor. It needs a way to internally increment each build attempt. I don't think there is a way around this.

No problem at all, I will remove it.

Thanks a lot for this effort m8. I was literally thinking about doing it myself when I find time. I will adapt chocolatey package one of next days to use this location.

Please make sure everything is statically built like before.

**Comment by majkinetor** [comment]
BTW, choco also requires something as minor build. Maybe its better to add .0 on your side, it looks better :)

**Comment by jftuga** [comment]
What is the best way to contact the Chocolatey admins (to add the link)?

**Comment by majkinetor** [comment]
Not talking about chocolatey admins, but less maintainers that keep links at the end of the download page (that is how I found now defunkt link):

http://greenwoodsoftware.com/less/download.html

**Comment by jftuga** [comment]
https://github.com/gwsw/less/issues/61#issuecomment-628623005

**Comment by majkinetor** [comment]
This is done, here is the new package:

https://chocolatey.org/packages/Less/5.61

**Comment by jftuga** [comment]
This is great!

I have also been learning about how to create Chocolatey packages. My first one is currently awaiting moderator review.

**Comment by jftuga** [comment]
@majkinetor 

The upstream released v562 (from v561).  I tweaked my automation script to fix a versioning bug.  Now, `less-v562.0` is avaliable on [Releases](https://github.com/jftuga/less-Windows/releases).

On your side, will your process automatically update the `Chocolatey` repo to this new version?

**Comment by majkinetor** [comment]
[Done](https://chocolatey.org/packages/less/5.62).
FYI, my automation scripts runs [nightly](https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1).
